name: Release
on:
  push:
    branches:
      - rel
jobs:
  Build-Release:
    name: build and release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm instanll
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: public
